### ISSUE TITLE
Add historical versions

### ISSUE THREAD

**Issue by multimeric** [conda-forge/ome-types-feedstock#22]
There are some historical releases that are on PyPI but not on conda-forge, including but not limited to:
* `0.2.10`
* `0.3.4`
* `0.4.3`

This is actually a blocker for `aicsimageio` [which I'm trying to fix](https://github.com/conda-forge/aicsimageio-feedstock/pull/32). It would be great if you could add some historical builds for these versions. I believe [this section](https://conda-forge.org/docs/maintainer/updating_pkgs/#maintaining-several-versions) explains how to do it.

**Comment by tlambert03** [comment]
Hi @multimeric,

Do you need all three of those versions?

**Comment by multimeric** [comment]
It's true that version of `aicsimageio` only needs `0.3.4`. But the more versions get added the better: I plan to submit PRs for the other missing `aicsimageio` versions as well.

**Comment by tlambert03** [comment]
ok, 0.3.4 is now on conda-forge staging: https://anaconda.org/cf-staging/ome-types

... should hopefully be on main soon.  Please let me know if it doesn't make it for some reason.

As for the other versions, please open a new issue for each specific version that you find you need (since I'm also time limited, i'd rather not go through the process of releasing every outdated historical release unless you definitely know you need it)

thanks!
